#!/usr/bin/env ruby

require 'ripper_tree'
require 'optparse'

options = { color: true, space_size: 8 }

OptionParser.new do |opt|
  opt.banner = 'Usage: rtree [options] programfile'
  opt.on('-e `command`', 'one line of script.') { |code| options[:code] = code }
  opt.on('-s `space size`', 'set space size [default size is 8].') { |size| options[:space_size] = size.to_i }
  opt.on('-v', '--version', 'display the version.') { options[:version] = true }
  opt.on('-c', '--[no-]color', 'color option') { options[:color] = false }

  opt.parse!(ARGV)
end

RipperTree::OPTIONS.merge!(options)

case
  when options[:code]
    puts RipperTree.create(options[:code])
  when options[:version]
    puts "RipperTree version: #{RipperTree::VERSION}"
  else
    puts RipperTree.create(File.read(ARGV.first, encoding: 'utf-8'))
end
